spring:
  datasource:
    url: jdbc:h2:~\fiapcreditcarddatabase;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  batch:
    initialize-schema: ALWAYS

file:
  path:  /Users/temp/lista_alunos.txt
  chunk: lista_alunos.txt




