drop table if exists TB_ALUNO;

create table tb_aluno
(
    id bigint generated by default as identity,
    nome varchar(255),
    numero_cartao varchar(255),
    ativo boolean,
    data_atualizacao timestamp,
    data_criacao timestamp not null,
    saldo decimal(19, 2),
    primary key (id)
)